version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
  pre_build:
    commands:
      - echo Pre-Build starting at `date`
      - pip install --upgrade pip
  build:
    commands:
      - echo Build starting at `date`
      - mkdir build
      - cd src/
      - pip install --target ./ pynacl boto3
      - zip -r fgc-rs-bot.zip .
      - aws lambda update-function-code --region=us-west-2 --function-name discord-fgc-rs-bot --zip-file fileb://fgc-rs-bot.zip
      - aws lambda publish-version --region=us-west-2 --function-name discord-fgc-rs-bot
  post_build:
    commands:
      - echo Build completed at `date`
artifacts:
  files:
    - '**/*'
  base-directory: src
