version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12.x
  pre_build:
    commands:
      - echo Pre-Build starting at `date`
      - pip install --upgrade pip
  build:
    commands:
      - echo Build starting at `date`
      - mkdir build
      - cd src/
      - pip install --target ./ pynacl boto3
  post_build:
    commands:
      - echo Build completed at `date`
artifacts:
  files:
    - '**/*'
  base-directory: src
