version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo Install starting at `date`
      - pip install --upgrade pip
      - pip install --target ./src -r requirements.txt
  build:
    commands:
      - echo Build starting at `date`
      - cd src
      - zip -r9 ../fgc-rs-bot.zip .
  post_build:
    commands:
      - cd ..
      - aws lambda update-function-code --region=us-west-2 --function-name discord-fgc-rs-bot --zip-file fileb://fgc-rs-bot.zip
      - echo Build completed at `date`
artifacts:
  files:
    - '**/*'
base-directory: src
