version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
  pre_build:
    commands:
      - echo Pre-Build starting at `date`
      - pip install --upgrade pip
  build:
    commands:
      - echo Build starting at `date`
      - pip install --target ./deps pynacl boto3 requests
      - cd deps
      - zip -r9 ../fgc-rs-bot.zip .
      - cd ../src
      - zip -g ../fgc-rs-bot.zip *
  post_build:
    commands:
      - aws lambda update-function-code --region=us-west-2 --function-name discord-fgc-rs-bot --zip-fiile fileb://fgc-rs-bot.zip
      - echo Build completed at `date`
