version: 0.2

phases:
  pre_build:
    commands:
      - echo Pre-Build starting at `date`
      - pip install --upgrade pip
  build:
    commands:
      - echo Build starting at `date`
      - pip install --target ./package pynacl
      - cd src/
  post_build:
    commands:
      - echo Build completed at `date`
artifacts:
  files:
    - fgc-rs-bot.zip
