version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo Install starting at `date`
      - pip install --upgrade pip
      - pip install --target ./src pynacl boto3 requests
  build:
    commands:
      - echo Build starting at `date`
      - cd src
      - aws cloudformation package --template-file template.yml --output-template-file template-out.yml --s3-bucket discord-fgc-rs-bot
artifacts:
  files:
    - template.yml
    - template-out.yml
  base-directory: src
