version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo Install starting at `date`
      - pip install --upgrade pip
      - pip install --target ./deps pynacl boto3 requests
  build:
    commands:
      - echo Build starting at `date`
      - cd deps
      - zip -r9 ../fgc-rs-bot.zip .
      - cd ../src
      - zip -g ../fgc-rs-bot.zip *
      - cd ..
  post_build:
    commands:
      - aws lambda update-function-code --region=us-west-2 --function-name discord-fgc-rs-bot --zip-file fileb://fgc-rs-bot.zip
      - echo Build completed at `date`
artifacts:
  files:
    - '**/*'
  base-directory: src
