version: 0.2

phases:
  pre_build:
    commands:
      - echo Pre-Build starting at `date`
      - pip install --upgrade pip
  build:
    commands:
      - echo Build starting at `date`
      - mkdir build
      - cd src/
      - pip install --target ./ pynacl boto3
      - zip -r ../build/fgc-rs-bot.zip ./
  post_build:
    commands:
      - echo Build completed at `date`
artifacts:
  files:
    - build/fgc-rs-bot.zip
